# Generated by Django 2.2.2 on 2021-07-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='pics')),
                ('image_captions', models.CharField(blank=True, max_length=60, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.CharField(max_length=500)),
            ],
        ),
    ]
