# Generated by Django 2.2.2 on 2021-07-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, upload_to='pics')),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
